#!/bin/bash -x
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IMAGE_DIR="$SCRIPT_DIR/../image"

PLANE0_KERNEL_DEFAULT="$IMAGE_DIR/fedora-kvm.vmlinuz"
PLANE0_INITRD_DEFAULT="$IMAGE_DIR/fedora-kvm.initrd"
PLANE0_DISK_DEFAULT="$IMAGE_DIR/fedora-kvm.raw"
PLANE1_SHIM_MAKE_DIR_DEFAULT="$SCRIPT_DIR/../../../build/src/loader"
PLANE1_SHIM_ELF_DEFAULT="$PLANE1_SHIM_MAKE_DIR_DEFAULT/lvbs-vtl1-pvh-shim.elf"
PLANE1_KERNEL_DEFAULT="$PLANE1_SHIM_ELF_DEFAULT"

run_both() {
	ENABLE_PLANE1=1 \
	PLANE0_KERNEL="${PLANE0_KERNEL:-$PLANE0_KERNEL_DEFAULT}" \
	PLANE0_INITRD="${PLANE0_INITRD:-$PLANE0_INITRD_DEFAULT}" \
	PLANE0_DISK="${PLANE0_DISK:-$PLANE0_DISK_DEFAULT}" \
	PLANE1_BOOT_VCPUS="${PLANE1_BOOT_VCPUS:-1}" \
	PLANE1_MAX_VCPUS="${PLANE1_MAX_VCPUS:-1}" \
	ALLOW_CUSTOM_PLANE1_ELF="${ALLOW_CUSTOM_PLANE1_ELF:-0}" \
	PLANE1_KERNEL="${PLANE1_KERNEL:-$PLANE1_KERNEL_DEFAULT}" \
	PLANE1_INITRD="${PLANE1_INITRD:-$PLANE0_INITRD_DEFAULT}" \
	PLANE1_SHIM_MAKE_DIR="${PLANE1_SHIM_MAKE_DIR:-$PLANE1_SHIM_MAKE_DIR_DEFAULT}" \
	PLANE1_SHIM_ELF="${PLANE1_SHIM_ELF:-$PLANE1_SHIM_ELF_DEFAULT}" \
	"$SCRIPT_DIR/create-ch-direct-planes.sh"
}

run_one() {
	ENABLE_PLANE1=0 \
	PLANE0_KERNEL="${PLANE0_KERNEL:-$PLANE0_KERNEL_DEFAULT}" \
	PLANE0_INITRD="${PLANE0_INITRD:-$PLANE0_INITRD_DEFAULT}" \
	PLANE0_DISK="${PLANE0_DISK:-$PLANE0_DISK_DEFAULT}" \
	"$SCRIPT_DIR/create-ch-direct-planes.sh"
}

#run_one
run_both

